version: "3.8"

name: "eddb2"
services:
  zookeeper:
    image: "bitnami/zookeeper:3.8"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    volumes:
      - "zookeeper_data:/bitnami"

  kafka:
    image: "bitnami/kafka:3.4"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_COMPRESSION_TYPE=gzip
    ports:
      - '9092:9092'
    volumes:
      - "kafka_data:/bitnami/kafka"
    depends_on:
      - zookeeper

  postgres:
    image: 'postgres:15-alpine'
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - '5432:5432'
    volumes:
      - "postgres_data:/var/lib/postgresql/data"


volumes:
  zookeeper_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./docker_data/zookeeper
  kafka_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./docker_data/kafka
  postgres_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./docker_data/postgres/
